spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lab-002-mybatis-xml?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456

mybatis:
  config-location: classpath:mybatis-config.xml  # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml  # 配置 Mapper XML 地址
  type-aliases-package: com.glj.java.labs.lab002.dataobject  # 配置数据库实体包路径
